use_frameworks!

platform :ios, '10.0'

target 'YMPlayer_Example' do
  pod 'YMPlayer', :path => '../'

  target 'YMPlayer_Tests' do
    inherit! :search_paths

    
  end
end

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      end
    end
  end